### ISSUE TITLE
Unable to change an account password

### ISSUE THREAD

**Issue by warlof** [ciaa-cnam/STOFMA#42]
With a standard account, i'm unable to change my password.
All fields are filled.

TypeError: Cannot read property '$modelValue' of undefined
    at n.$scope.update (http://bde-ciaa.fr/min/production.1442494194641.min.js:20:26962)
    at fn (eval at <anonymous> (http://bde-ciaa.fr/min/production.1442494194641.min.js:4:8803), <anonymous>:4:313)
    at f (http://bde-ciaa.fr/min/production.1442494194641.min.js:4:29413)
    at n.$eval (http://bde-ciaa.fr/min/production.1442494194641.min.js:3:378)
    at n.$apply (http://bde-ciaa.fr/min/production.1442494194641.min.js:3:608)
    at HTMLButtonElement.<anonymous> (http://bde-ciaa.fr/min/production.1442494194641.min.js:4:29465)
    at HTMLButtonElement.Ef.c (http://bde-ciaa.fr/min/production.1442494194641.min.js:1:14914)

**Comment by corentindesfarges** [comment]
We have identified the source of this error (thx @edimitchel).
It will be fixed asap.

Thanks for your feedback.
